"""add hush_hush to users

Revision ID: 0d87386a32d3
Revises: 369275284a70
Create Date: 2026-08-22 14:09:53.372081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d87386a32d3'
down_revision: Union[str, Sequence[str], None] = '369275284a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hush_hush', sa.String(), nullable=False, server_default='temp_placeholder'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hush_hush')
    # ### end Alembic commands ###
