"""add blacklisted_tokens table

Revision ID: 4888878d856c
Revises: d327dac89186
Create Date: 2026-09-04 15:24:51.669726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4888878d856c'
down_revision: Union[str, Sequence[str], None] = 'd327dac89186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
    # ### end Alembic commands ###
